// AUTO-GENERATED by tooling/icon-atlas/build.mjs — do not edit.
// Tinted lucide icon PNGs for <ViroIcon> (rendered via <ViroImage>).
export type IconName = 'pencil' | 'highlighter' | 'eraser' | 'undo-2' | 'redo-2' | 'trash-2' | 'x' | 'chevron-up' | 'chevron-down' | 'chevron-left' | 'chevron-right' | 'scan' | 'camera' | 'sparkles' | 'rotate-ccw' | 'search' | 'play' | 'pause' | 'footprints' | 'swords' | 'zap'
export type IconTint = 'white' | 'amber' | 'muted'

export const ICON_PNG: Record<IconName, Record<IconTint, number>> = {
  'pencil': {
    white: require('./png/pencil-white.png'),
    amber: require('./png/pencil-amber.png'),
    muted: require('./png/pencil-muted.png'),
  },
  'highlighter': {
    white: require('./png/highlighter-white.png'),
    amber: require('./png/highlighter-amber.png'),
    muted: require('./png/highlighter-muted.png'),
  },
  'eraser': {
    white: require('./png/eraser-white.png'),
    amber: require('./png/eraser-amber.png'),
    muted: require('./png/eraser-muted.png'),
  },
  'undo-2': {
    white: require('./png/undo-2-white.png'),
    amber: require('./png/undo-2-amber.png'),
    muted: require('./png/undo-2-muted.png'),
  },
  'redo-2': {
    white: require('./png/redo-2-white.png'),
    amber: require('./png/redo-2-amber.png'),
    muted: require('./png/redo-2-muted.png'),
  },
  'trash-2': {
    white: require('./png/trash-2-white.png'),
    amber: require('./png/trash-2-amber.png'),
    muted: require('./png/trash-2-muted.png'),
  },
  'x': {
    white: require('./png/x-white.png'),
    amber: require('./png/x-amber.png'),
    muted: require('./png/x-muted.png'),
  },
  'chevron-up': {
    white: require('./png/chevron-up-white.png'),
    amber: require('./png/chevron-up-amber.png'),
    muted: require('./png/chevron-up-muted.png'),
  },
  'chevron-down': {
    white: require('./png/chevron-down-white.png'),
    amber: require('./png/chevron-down-amber.png'),
    muted: require('./png/chevron-down-muted.png'),
  },
  'chevron-left': {
    white: require('./png/chevron-left-white.png'),
    amber: require('./png/chevron-left-amber.png'),
    muted: require('./png/chevron-left-muted.png'),
  },
  'chevron-right': {
    white: require('./png/chevron-right-white.png'),
    amber: require('./png/chevron-right-amber.png'),
    muted: require('./png/chevron-right-muted.png'),
  },
  'scan': {
    white: require('./png/scan-white.png'),
    amber: require('./png/scan-amber.png'),
    muted: require('./png/scan-muted.png'),
  },
  'camera': {
    white: require('./png/camera-white.png'),
    amber: require('./png/camera-amber.png'),
    muted: require('./png/camera-muted.png'),
  },
  'sparkles': {
    white: require('./png/sparkles-white.png'),
    amber: require('./png/sparkles-amber.png'),
    muted: require('./png/sparkles-muted.png'),
  },
  'rotate-ccw': {
    white: require('./png/rotate-ccw-white.png'),
    amber: require('./png/rotate-ccw-amber.png'),
    muted: require('./png/rotate-ccw-muted.png'),
  },
  'search': {
    white: require('./png/search-white.png'),
    amber: require('./png/search-amber.png'),
    muted: require('./png/search-muted.png'),
  },
  'play': {
    white: require('./png/play-white.png'),
    amber: require('./png/play-amber.png'),
    muted: require('./png/play-muted.png'),
  },
  'pause': {
    white: require('./png/pause-white.png'),
    amber: require('./png/pause-amber.png'),
    muted: require('./png/pause-muted.png'),
  },
  'footprints': {
    white: require('./png/footprints-white.png'),
    amber: require('./png/footprints-amber.png'),
    muted: require('./png/footprints-muted.png'),
  },
  'swords': {
    white: require('./png/swords-white.png'),
    amber: require('./png/swords-amber.png'),
    muted: require('./png/swords-muted.png'),
  },
  'zap': {
    white: require('./png/zap-white.png'),
    amber: require('./png/zap-amber.png'),
    muted: require('./png/zap-muted.png'),
  },
}
