package com.moyolearn.app

import android.app.Activity
import android.app.Application
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import com.facebook.react.runtime.ReactHostImpl

/**
 * VRActivity — generated by @reactvision/react-viro Expo plugin.
 * Carries com.oculus.intent.category.VR so Horizon OS grants exclusive
 * OpenXR display access. Mounts the "VRQuestScene" React root component.
 * Launch via NativeModules.VRLauncher.launchVRScene().
 *
 * Lifecycle (requires React Native >= 0.83 / Expo >= 55):
 *   VRActivity and MainActivity share one ReactHostImpl singleton. On Quest,
 *   VRActivity launches into a separate task (FLAG_ACTIVITY_NEW_TASK), so
 *   MainActivity.onPause is dispatched *later* via ActivityManager IPC —
 *   often after VRActivity.onResume has already promoted the host to RESUMED
 *   with currentActivity = VRActivity. When that delayed onPause arrives,
 *   the standard delegate calls onHostPause(MainActivity); the identity-
 *   mismatch assertion is downgraded to a warning by
 *   skipActivityIdentityAssertionOnHostPause (set in VRLauncherModule before
 *   startActivity), but the rest of onHostPause runs unconditionally:
 *   devSupport is disabled and JavaTimerManager clears its TIMERS_EVENTS
 *   callback. Result: timers / requestAnimationFrame stop, Metro Fast Refresh
 *   dies.
 *
 *   We catch this by listening for that delayed MainActivity.onPause via
 *   Application.ActivityLifecycleCallbacks.onActivityPaused(other) and re-
 *   promoting the host on the main looper. A Handler.post inside our own
 *   onResume would fire too early (the ActivityManager hasn't queued
 *   MainActivity.onPause yet), which is why we hook the actual pause event.
 *
 *   On exit, VRActivity.onPause runs while currentActivity == this, so the
 *   identity assertion passes; MainActivity.onResume then re-promotes via
 *   its standard delegate. We do *not* re-promote on a self-pause — the
 *   onActivityPaused callback skips when other === this.
 *
 * Mutual exclusion with MainActivity:
 *   Quest will happily run MainActivity (panel) and VRActivity (immersive) at
 *   the same time if the user taps the app icon in the dock while VR is
 *   running. The same Application.ActivityLifecycleCallbacks finishes self
 *   when any other Activity in this app resumes — returning the user cleanly
 *   to the panel.
 *
 * Surface cleanup on destroy:
 *   When VRActivity is destroyed we unload its React surface (reactSurface.stop()
 *   in bridgeless arch) so its component tree — including all VRT* components
 *   — is unmounted. Without this, the React surface stayed alive in the shared
 *   ReactHost across VR re-entries, and on the second/third VR launch each
 *   stale surface remounted alongside the fresh one. The C++ scene-graph
 *   resolves a click hit to a single viewTag, but multiple VRTComponents
 *   claimed it across surfaces — most with a ReactContext bound to a
 *   destroyed VRActivity. Click events to the stale ReactContexts crashed in
 *   ComponentEventDelegate as IllegalArgumentException SoftExceptions and were
 *   silently dropped, so onClick took dozens of presses to register.
 *   We still no-op the *delegate* onDestroy() so MainActivity keeps its
 *   ReactHost; we only stop the surface explicitly.
 */
class VRActivity : ReactActivity() {

    private val mainHandler = Handler(Looper.getMainLooper())
    private var lifecycleCallbacks: Application.ActivityLifecycleCallbacks? = null

    // Set true on every VRActivity.onResume; consumed by the first
    // onActivityPaused(other) that follows. One-shot — defends against the
    // single MainActivity.onPause that the NEW_TASK ordering schedules late.
    // Without one-shot semantics, every subsequent foreign pause would re-fire
    // ReactHostImpl.onHostResume, which re-fires every LifecycleEventListener
    // (AppState → "active" → ViroXRSceneNavigator's AppState handler calls
    // launchVRScene() again → visible scene flicker).
    private var expectingForeignPause = false

    override fun getMainComponentName(): String = "VRQuestScene"

    override fun createReactActivityDelegate(): ReactActivityDelegate =
        object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {
            // VRActivity destruction MUST NOT tear down the shared ReactHost.
            // MainActivity is still alive (and re-foreground after VR exit) and
            // depends on the same ReactContext. The standard delegate's
            // onDestroy forwards to ReactHostImpl.onHostDestroy(VR), which
            // fires LifecycleEventListener.onHostDestroy on every native module
            // — releasing native resources MainActivity still uses. The next
            // Cmd+R reload then runs the JS bundle re-init against a partially
            // destroyed native side and fails with
            //   [runtime not ready]: TypeError: Cannot read property
            //   'EventEmitter' of undefined
            // followed by AppRegistryBinding::stopSurface failed and the
            // surface never recovers. By no-op'ing onDestroy here, host
            // destruction is left to MainActivity's standard delegate (the real
            // last activity). The surface itself is stopped explicitly in
            // VRActivity.onDestroy() below.
            override fun onDestroy() {
                // intentionally no-op — see comment above
            }
        }

    override fun onResume() {
        super.onResume()  // delegate.onResume() -> reactHost.onHostResume(this)
        expectingForeignPause = true
    }

    // onPause not overridden: the default delegate forwards to
    // reactHost.onHostPause(this) while currentActivity matches us, which is
    // what we want.

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val callbacks = object : Application.ActivityLifecycleCallbacks {
            override fun onActivityResumed(other: Activity) {
                if (other !== this@VRActivity && !isFinishing && !isDestroyed) {
                    finish()
                }
            }
            override fun onActivityPaused(other: Activity) {
                if (other === this@VRActivity || isFinishing || isDestroyed) return
                if (!expectingForeignPause) return
                expectingForeignPause = false
                // MainActivity.onPause was dispatched after our onResume (the
                // NEW_TASK race). The standard delegate already called
                // onHostPause(MainActivity), demoting the host to PAUSED and
                // disabling devSupport / clearing JavaTimerManager's frame
                // callback. Re-promote so VR keeps timers + Fast Refresh.
                mainHandler.post {
                    if (isFinishing || isDestroyed) return@post
                    (reactHost as? ReactHostImpl)?.onHostResume(this@VRActivity)
                }
            }
            override fun onActivityCreated(a: Activity, b: Bundle?) {}
            override fun onActivityStarted(a: Activity) {}
            override fun onActivityStopped(a: Activity) {}
            override fun onActivitySaveInstanceState(a: Activity, b: Bundle) {}
            override fun onActivityDestroyed(a: Activity) {}
        }
        application.registerActivityLifecycleCallbacks(callbacks)
        lifecycleCallbacks = callbacks
    }

    override fun onDestroy() {
        // Stop the React surface attached to this VRActivity so its component
        // tree unmounts cleanly. In bridgeless arch this calls
        // reactSurface.stop() + reactSurface = null, leaving the shared
        // ReactHost intact for MainActivity. Without this the React tree from
        // each VR session piles up across re-entries and stale VRTComponents
        // intercept hit-tested viewTags with dead ReactContexts, breaking
        // onClick / onHover until you press dozens of times.
        try {
            reactDelegate?.unloadApp()
        } catch (t: Throwable) {
            android.util.Log.w("VRActivity", "reactDelegate.unloadApp() failed", t)
        }
        lifecycleCallbacks?.let { application.unregisterActivityLifecycleCallbacks(it) }
        lifecycleCallbacks = null
        mainHandler.removeCallbacksAndMessages(null)
        super.onDestroy()
    }
}
