/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    guardianships: Guardianship;
    consents: Consent;
    skills: Skill;
    misconceptions: Misconception;
    sessionTranscripts: SessionTranscript;
    tutorSessions: TutorSession;
    tutorMessages: TutorMessage;
    studentModelFacts: StudentModelFact;
    safetyEvents: SafetyEvent;
    incidentReports: IncidentReport;
    sessionSummaries: SessionSummary;
    organizations: Organization;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    guardianships: GuardianshipsSelect<false> | GuardianshipsSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    misconceptions: MisconceptionsSelect<false> | MisconceptionsSelect<true>;
    sessionTranscripts: SessionTranscriptsSelect<false> | SessionTranscriptsSelect<true>;
    tutorSessions: TutorSessionsSelect<false> | TutorSessionsSelect<true>;
    tutorMessages: TutorMessagesSelect<false> | TutorMessagesSelect<true>;
    studentModelFacts: StudentModelFactsSelect<false> | StudentModelFactsSelect<true>;
    safetyEvents: SafetyEventsSelect<false> | SafetyEventsSelect<true>;
    incidentReports: IncidentReportsSelect<false> | IncidentReportsSelect<true>;
    sessionSummaries: SessionSummariesSelect<false> | SessionSummariesSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Doc 31 §2 voice band. Drives tutor voice and the crisis register.
   */
  gradeBand?: ('k-2' | '3-5' | '6-8' | '9-12') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guardianships".
 */
export interface Guardianship {
  id: number;
  guardianAuthId: string;
  learnerAuthId: string;
  relationship: 'guardian' | 'parent' | 'carer';
  status: 'active' | 'invited' | 'revoked';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  learnerAuthId: string;
  guardianAuthId: string;
  method: 'email-plus' | 'text-plus' | 'kba' | 'card';
  scope: string;
  policyVersion: string;
  evidenceRef?: string | null;
  grantedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  slug: string;
  title: string;
  subject: 'math' | 'reading' | 'writing' | 'science';
  band: 'elementary' | 'junior-high' | 'high-school';
  prerequisites?: (number | Skill)[] | null;
  tutorable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "misconceptions".
 */
export interface Misconception {
  id: number;
  tag: string;
  skill: number | Skill;
  sentence: string;
  strategy: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessionTranscripts".
 */
export interface SessionTranscript {
  id: number;
  sessionId: string;
  learnerAuthId: string;
  turns:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  capturedAt: string;
  expiresAt: string;
  distilledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorSessions".
 */
export interface TutorSession {
  id: number;
  sessionId: string;
  learnerAuthId: string;
  problem?: string | null;
  messages:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  closedAt?: string | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorMessages".
 */
export interface TutorMessage {
  id: number;
  messageId: string;
  sessionId: string;
  learnerAuthId: string;
  role: 'learner' | 'tutor';
  text: string;
  attachments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentModelFacts".
 */
export interface StudentModelFact {
  id: number;
  factId: string;
  learnerAuthId: string;
  kind: 'mastery' | 'misconception' | 'review' | 'interest' | 'scaffolding';
  skill?: (number | null) | Skill;
  sentence: string;
  detail:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  derivedFrom: string[];
  observedAt: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "safetyEvents".
 */
export interface SafetyEvent {
  id: number;
  eventId: string;
  learnerAuthId: string;
  sessionId?: string | null;
  category: 'crisis' | 'safety' | 'boundary' | 'paused';
  tier?: ('S1' | 'S2' | 'S3' | 'S4') | null;
  disposition: 'crisis' | 'blocked' | 'redirect' | 'paused';
  stoppedAt: string;
  trace:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  guardianVisible: boolean;
  occurredAt: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidentReports".
 */
export interface IncidentReport {
  id: number;
  incidentId: string;
  source: 'automated' | 'submitted';
  reporterRole: 'system' | 'tutor' | 'staff' | 'guardian' | 'learner';
  reporterAuthId?: string | null;
  anonymous: boolean;
  subjectLearnerAuthId: string;
  relatedSessionId?: string | null;
  relatedEventId?: string | null;
  category:
    | 'profanity'
    | 'sexual-content'
    | 'bullying'
    | 'pii-shared'
    | 'violence'
    | 'substances'
    | 'self-harm'
    | 'abuse-disclosure'
    | 'tutor-behavior'
    | 'safety-concern'
    | 'other';
  severity: 'S1' | 'S2' | 'S3' | 'S4';
  occurredAt: string;
  summary: string;
  transcriptExcerpt?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attachmentIds?: string[] | null;
  immediateActionTaken?: string | null;
  status: 'new' | 'triaged' | 'in-review' | 'actioned' | 'resolved' | 'closed';
  assigneeAuthId?: string | null;
  slaDueAt?: string | null;
  guardianVisible: boolean;
  guardianNotifiedAt?: string | null;
  reviewPagedAt?: string | null;
  guardianAcknowledgedAt?: string | null;
  resolution?: string | null;
  timeline:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  legalHold?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessionSummaries".
 */
export interface SessionSummary {
  id: number;
  sessionId: string;
  learnerAuthId: string;
  sessionKind: 'ai-tutor' | 'human-tutor' | 'hybrid';
  band: 'k-2' | '3-5' | '6-8' | '9-12';
  headline: string;
  workedOn:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  problems:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mastery:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  effortMoment?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  nextUp: string;
  homeSupport:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  facts:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidenceRefs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generator:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  safetyScreened: boolean;
  tutorDraft?: string | null;
  tutorApprovedByAuthId?: string | null;
  status: 'generating' | 'draft' | 'published' | 'suppressed';
  publishedAt?: string | null;
  guardianViewedAt?: string | null;
  suppressionReason?: string | null;
  suppressedAt?: string | null;
  teacherShare?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  digestBatchId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * The tenant key. This is the value rows carry as orgId.
   */
  slug: string;
  kind: 'tutoring' | 'school' | 'district';
  logoUrl?: string | null;
  logoAspect?: ('square' | 'wide') | null;
  brandAccent?: ('ember' | 'gold' | 'forest' | 'sky' | 'rose') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  orgId: string;
  family: string;
  learnerRef?: string | null;
  learner?: string | null;
  subject?: string | null;
  stage: 'Inquiry' | 'Trial scheduled' | 'Trial completed' | 'Proposal' | 'Enrolled' | 'At risk';
  owner?: string | null;
  valueCents?: number | null;
  currency?: string | null;
  sessions?: number | null;
  nextSessionAt?: string | null;
  needsAttention?: boolean | null;
  attendancePct?: number | null;
  cohortSize?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'guardianships';
        value: number | Guardianship;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'misconceptions';
        value: number | Misconception;
      } | null)
    | ({
        relationTo: 'sessionTranscripts';
        value: number | SessionTranscript;
      } | null)
    | ({
        relationTo: 'tutorSessions';
        value: number | TutorSession;
      } | null)
    | ({
        relationTo: 'tutorMessages';
        value: number | TutorMessage;
      } | null)
    | ({
        relationTo: 'studentModelFacts';
        value: number | StudentModelFact;
      } | null)
    | ({
        relationTo: 'safetyEvents';
        value: number | SafetyEvent;
      } | null)
    | ({
        relationTo: 'incidentReports';
        value: number | IncidentReport;
      } | null)
    | ({
        relationTo: 'sessionSummaries';
        value: number | SessionSummary;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  gradeBand?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guardianships_select".
 */
export interface GuardianshipsSelect<T extends boolean = true> {
  guardianAuthId?: T;
  learnerAuthId?: T;
  relationship?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  learnerAuthId?: T;
  guardianAuthId?: T;
  method?: T;
  scope?: T;
  policyVersion?: T;
  evidenceRef?: T;
  grantedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subject?: T;
  band?: T;
  prerequisites?: T;
  tutorable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "misconceptions_select".
 */
export interface MisconceptionsSelect<T extends boolean = true> {
  tag?: T;
  skill?: T;
  sentence?: T;
  strategy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessionTranscripts_select".
 */
export interface SessionTranscriptsSelect<T extends boolean = true> {
  sessionId?: T;
  learnerAuthId?: T;
  turns?: T;
  capturedAt?: T;
  expiresAt?: T;
  distilledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorSessions_select".
 */
export interface TutorSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  learnerAuthId?: T;
  problem?: T;
  messages?: T;
  closedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorMessages_select".
 */
export interface TutorMessagesSelect<T extends boolean = true> {
  messageId?: T;
  sessionId?: T;
  learnerAuthId?: T;
  role?: T;
  text?: T;
  attachments?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentModelFacts_select".
 */
export interface StudentModelFactsSelect<T extends boolean = true> {
  factId?: T;
  learnerAuthId?: T;
  kind?: T;
  skill?: T;
  sentence?: T;
  detail?: T;
  derivedFrom?: T;
  observedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "safetyEvents_select".
 */
export interface SafetyEventsSelect<T extends boolean = true> {
  eventId?: T;
  learnerAuthId?: T;
  sessionId?: T;
  category?: T;
  tier?: T;
  disposition?: T;
  stoppedAt?: T;
  trace?: T;
  guardianVisible?: T;
  occurredAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidentReports_select".
 */
export interface IncidentReportsSelect<T extends boolean = true> {
  incidentId?: T;
  source?: T;
  reporterRole?: T;
  reporterAuthId?: T;
  anonymous?: T;
  subjectLearnerAuthId?: T;
  relatedSessionId?: T;
  relatedEventId?: T;
  category?: T;
  severity?: T;
  occurredAt?: T;
  summary?: T;
  transcriptExcerpt?: T;
  attachmentIds?: T;
  immediateActionTaken?: T;
  status?: T;
  assigneeAuthId?: T;
  slaDueAt?: T;
  guardianVisible?: T;
  guardianNotifiedAt?: T;
  reviewPagedAt?: T;
  guardianAcknowledgedAt?: T;
  resolution?: T;
  timeline?: T;
  expiresAt?: T;
  legalHold?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessionSummaries_select".
 */
export interface SessionSummariesSelect<T extends boolean = true> {
  sessionId?: T;
  learnerAuthId?: T;
  sessionKind?: T;
  band?: T;
  headline?: T;
  workedOn?: T;
  problems?: T;
  mastery?: T;
  effortMoment?: T;
  nextUp?: T;
  homeSupport?: T;
  facts?: T;
  evidenceRefs?: T;
  generator?: T;
  safetyScreened?: T;
  tutorDraft?: T;
  tutorApprovedByAuthId?: T;
  status?: T;
  publishedAt?: T;
  guardianViewedAt?: T;
  suppressionReason?: T;
  suppressedAt?: T;
  teacherShare?: T;
  digestBatchId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  logoUrl?: T;
  logoAspect?: T;
  brandAccent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  orgId?: T;
  family?: T;
  learnerRef?: T;
  learner?: T;
  subject?: T;
  stage?: T;
  owner?: T;
  valueCents?: T;
  currency?: T;
  sessions?: T;
  nextSessionAt?: T;
  needsAttention?: T;
  attendancePct?: T;
  cohortSize?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'users'
      | 'media'
      | 'guardianships'
      | 'consents'
      | 'skills'
      | 'misconceptions'
      | 'sessionTranscripts'
      | 'tutorSessions'
      | 'tutorMessages'
      | 'studentModelFacts'
      | 'safetyEvents'
      | 'incidentReports'
      | 'sessionSummaries'
      | 'organizations'
      | 'leads';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'users'
          | 'media'
          | 'guardianships'
          | 'consents'
          | 'skills'
          | 'misconceptions'
          | 'sessionTranscripts'
          | 'tutorSessions'
          | 'tutorMessages'
          | 'studentModelFacts'
          | 'safetyEvents'
          | 'incidentReports'
          | 'sessionSummaries'
          | 'organizations'
          | 'leads'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}