import 'server-only';
// Bunny Stream credentials for a resumable video upload.
//
// A DIFFERENT scheme from Storage, and the difference is not cosmetic. Storage
// is S3-compatible, so it takes SigV4 over a canonical request. Stream is
// Bunny's own: a video row is created server-side first, then the client is
// given `sha256(libraryId + apiKey + expiry + videoId)` and uploads with TUS.
//
// Two consequences worth stating, because they shape the UI:
//   1. The videoId exists BEFORE any bytes move, so progress can be attributed
//      to a real record from the first chunk.
//   2. Upload completing is not the video being ready. Bunny transcodes
//      afterwards — QUEUED, PROCESSING, ENCODING, FINISHED — which is why doc 29
//      §4 calls for a two-phase progress model for video and not for images.
// SOT: docs/decisions/bunny-storage-presign-spike.md
// SOT-KEYWORDS: bunny stream tus video presign signature service upload
import type { ProtectedCtx } from '../../core/protected-operation.ts';

export interface StreamUploadCredential {
  /** TUS endpoint. Always this host — Stream is not per-region. */
  endpoint: string;
  libraryId: string;
  videoId: string;
  /** Unix seconds. The signature is only valid until this moment. */
  expire: number;
  /** sha256(libraryId + apiKey + expire + videoId), hex. */
  signature: string;
  /** Where the finished video plays from, once transcoding completes. */
  playbackUrl: string;
  /** Poster frame, generated by Bunny during transcode. */
  thumbnailUrl: string;
}

/** Repository port — creates the video row and returns its id. */
export type CreateStreamVideo = (title: string) => Promise<string>;

/** Repository port — signs an existing videoId. Never runs on a client. */
export type SignStreamUpload = (videoId: string) => Omit<StreamUploadCredential, 'videoId'>;

export class StreamRejected extends Error {}

/**
 * Creates the video row, then signs it.
 *
 * The title is the only thing a caller supplies, and it is trimmed and capped
 * rather than trusted — it is shown in Bunny's dashboard and returned in API
 * responses, so an unbounded string is somebody else's problem later.
 */
export async function presignStreamUpload(
  _ctx: ProtectedCtx,
  title: string,
  createVideo: CreateStreamVideo,
  signUpload: SignStreamUpload,
): Promise<StreamUploadCredential> {
  const clean = title.trim().slice(0, 200);
  if (!clean) throw new StreamRejected('A video needs a title.');

  const videoId = await createVideo(clean);
  return { ...signUpload(videoId), videoId };
}
