// build.mjs — panel icon generator for <ViroIcon>.
//
// HISTORY: v1 rendered a signed-distance-field atlas sampled by a custom Viro
// shaderModifier. On-device the icons came out INVISIBLE — the surface-stage
// modifier ran before diffuse_color held the atlas sample, so alpha resolved to
// 0 everywhere. Rather than chase Viro's shader-pipeline ordering blind, this
// v2 uses the one path we KNOW renders on the PICO: plain <ViroImage> PNGs (the
// same component that draws the Pokémon artwork). No atlas, no UV rects, no
// custom material, no shader.
//
// For each icon × tint it rasterises the lucide-react-native (ISC) SVG with the
// stroke recoloured, and writes a transparent PNG. ViroIcon require()s the map.
//
// Run from repo root:  node tooling/icon-atlas/build.mjs
import sharp from 'sharp'
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const LUCIDE = join(ROOT, 'node_modules/lucide-react-native/dist/cjs/icons')
const OUT_DIR = join(ROOT, 'packages/ui/xr/premium/icon-atlas')
const PNG_DIR = join(OUT_DIR, 'png')

// Curated panel/flyout icon set (kebab-case lucide names). Add here to grow it.
const ICONS = [
  // MoyoLearn's tool rail — every one of these is a ViroButton in the left
  // panel, so each needs its own PNG per state. ViroButton takes an IMAGE and
  // nothing else (source / hoverSource / clickSource); there is no text.
  'pencil',
  'highlighter',
  'eraser',
  'undo-2',
  'redo-2',
  'trash-2',
  // poke-xr's original panel set, kept so the vendored component still finds
  // every icon it references.
  'x',
  'chevron-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'scan',
  'camera',
  'sparkles',
  'rotate-ccw',
  'search',
  'play',
  'pause',
  'footprints',
  'swords',
  'zap',
]

/*
  Panel palette. White = default, amber = hover/active, muted = disabled.
  Kept as poke-xr's three tints rather than MoyoLearn's semantic tokens: the
  vendored panel's own chrome is built against these names, and a fourth tint
  would be a second source of truth for the same three states.
*/
const TINTS = { white: '#FFFFFF', amber: '#F2B705', muted: '#8A8474' }
const SIZE = 128 // px per icon PNG (supersampled vs the ~48px on-panel size)

function loadIconNode(name) {
  const src = readFileSync(join(LUCIDE, `${name}.js`), 'utf8')
  const m = src.match(/createLucideIcon\(\s*"[^"]+"\s*,\s*(\[[\s\S]*?\])\s*\)/)
  if (!m) throw new Error(`could not parse icon node for "${name}"`)
  // eslint-disable-next-line no-new-func
  return Function(`"use strict"; return (${m[1]});`)()
}

function buildSvg(nodeArray, stroke) {
  const els = nodeArray
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => k !== 'key')
        .map(([k, v]) => `${k}="${v}"`)
        .join(' ')
      return `<${tag} ${a}/>`
    })
    .join('')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 24 24" fill="none" stroke="${stroke}" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">${els}</svg>`
}

async function main() {
  rmSync(PNG_DIR, { recursive: true, force: true })
  mkdirSync(PNG_DIR, { recursive: true })

  for (const name of ICONS) {
    const node = loadIconNode(name)
    for (const [tint, hex] of Object.entries(TINTS)) {
      const svg = buildSvg(node, hex)
      await sharp(Buffer.from(svg)).resize(SIZE, SIZE, { fit: 'fill' }).png().toFile(join(PNG_DIR, `${name}-${tint}.png`))
    }
    console.log(`icon ✓ ${name}`)
  }

  // Static require map — ViroImage needs literal require() calls, so emit them.
  const tintKeys = Object.keys(TINTS)
  const names = ICONS.map((n) => `'${n}'`).join(' | ')
  const entries = ICONS.map((name) => {
    const perTint = tintKeys
      .map((t) => `    ${t}: require('./png/${name}-${t}.png'),`)
      .join('\n')
    return `  '${name}': {\n${perTint}\n  },`
  }).join('\n')

  const ts = `// AUTO-GENERATED by tooling/icon-atlas/build.mjs — do not edit.
// Tinted lucide icon PNGs for <ViroIcon> (rendered via <ViroImage>).
export type IconName = ${names}
export type IconTint = ${tintKeys.map((t) => `'${t}'`).join(' | ')}

export const ICON_PNG: Record<IconName, Record<IconTint, number>> = {
${entries}
}
`
  writeFileSync(join(OUT_DIR, 'icons.ts'), ts)
  console.log(`\n${ICONS.length} icons × ${tintKeys.length} tints → ${PNG_DIR}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
