// build-buttons.mjs — button FACES for <ViroButton> in the spatial tool panel.
//
// WHAT A FACE IS, AND WHAT IT DELIBERATELY IS NOT. `ViroButton` renders three
// `ViroImage`s and nothing else — read its source: `source` / `hoverSource` /
// `clickSource`, no `children`. So the button's PLATE and its GLYPH are baked
// here, one PNG per state, because neither changes at runtime.
//
// THE LABEL IS NOT BAKED. It is a real `ViroText` node the panel draws over the
// button: a baked word cannot be re-read when the tutor is renamed or the copy
// is localised, and it would force a PNG rebuild for a text change. The
// colour-selector button carries no label at all — its face IS the swatch.
//
// It follows the same finding the icon atlas is built on — the one path proven
// to render on this hardware is a plain textured quad, not a shader. A pill
// drawn as geometry plus `ViroText` would be three nodes fighting for one ray;
// a face is one image and one hit target.
//
// Run from the repo root:  node tooling/icon-atlas/build-buttons.mjs
// SOT: tooling/icon-atlas/build.mjs · packages/ui/xr/premium/PremiumXRMediaPanel.tsx
// SOT-KEYWORDS: viro button face png label baked icon atlas spatial tool panel

import sharp from 'sharp';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const LUCIDE = join(ROOT, 'node_modules/lucide-react-native/dist/cjs/icons');
const OUT_DIR = join(ROOT, 'packages/ui/xr/premium/button-faces');
const PNG_DIR = join(OUT_DIR, 'png');

/** id → [lucide icon, label]. The id is what the panel names the button by. */
const BUTTONS = {
  pen: ['pencil', 'Pen'],
  highlighter: ['highlighter', 'Highlighter'],
  eraser: ['eraser', 'Eraser'],
  undo: ['undo-2', 'Undo'],
  redo: ['redo-2', 'Redo'],
  clear: ['trash-2', 'Clear'],
  ask: ['sparkles', 'Ask Natalie'],
};

/*
  Three states, and the contrast for each was chosen not eyeballed. Ink on paper
  is 15.9:1; ink on amber is 9.7:1. Both clear AA for the 44 px type at this
  size, and the hover/active state is a FILL change rather than a colour-only
  cue, so it survives a colour-blind reader.
*/
const STATES = {
  rest: { plate: '#F5F0E1', ink: '#17150F' },
  hover: { plate: '#F2B705', ink: '#17150F' },
  active: { plate: '#D8232A', ink: '#FFFFFF' },
};

/* 4:1, supersampled against the ~0.5 m × 0.125 m the panel draws them at. */
const W = 512;
const H = 128;
const RADIUS = 22;
const PAD = 26;
const GLYPH = 56;

function loadIconNode(name) {
  const src = readFileSync(join(LUCIDE, `${name}.js`), 'utf8');
  const m = src.match(/createLucideIcon\(\s*"[^"]+"\s*,\s*(\[[\s\S]*?\])\s*\)/);
  if (!m) throw new Error(`could not parse icon node for "${name}"`);
  return Function(`"use strict"; return (${m[1]});`)();
}

function glyphMarkup(nodeArray, stroke) {
  return nodeArray
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => k !== 'key')
        .map(([k, v]) => `${k}="${v}"`)
        .join(' ');
      return `<${tag} ${a}/>`;
    })
    .join('');
}

function face(nodeArray, { plate, ink }) {
  const glyphX = PAD;
  const glyphY = (H - GLYPH) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect x="2" y="2" width="${W - 4}" height="${H - 4}" rx="${RADIUS}" fill="${plate}"/>
  <g transform="translate(${glyphX} ${glyphY}) scale(${GLYPH / 24})"
     fill="none" stroke="${ink}" stroke-width="2.2"
     stroke-linecap="round" stroke-linejoin="round">${glyphMarkup(nodeArray)}</g>
</svg>`;
}

async function main() {
  rmSync(PNG_DIR, { recursive: true, force: true });
  mkdirSync(PNG_DIR, { recursive: true });

  const entries = [];
  for (const [id, [icon]] of Object.entries(BUTTONS)) {
    const node = loadIconNode(icon);
    const states = {};
    for (const [state, colours] of Object.entries(STATES)) {
      const file = `${id}-${state}.png`;
      await sharp(Buffer.from(face(node, colours))).png().toFile(join(PNG_DIR, file));
      states[state] = file;
      process.stdout.write(`face ✓ ${file}\n`);
    }
    entries.push([id, states]);
  }

  const body = entries
    .map(
      ([id, states]) =>
        `  '${id}': {\n` +
        Object.entries(states)
          .map(([state, file]) => `    ${state}: require('./png/${file}'),`)
          .join('\n') +
        '\n  },',
    )
    .join('\n');

  writeFileSync(
    join(OUT_DIR, 'faces.ts'),
    `// AUTO-GENERATED by tooling/icon-atlas/build-buttons.mjs — do not edit.
// Button faces for <ViroButton>: a rounded plate and the lucide glyph, one PNG
// per state. The LABEL is not here — the panel draws it as a ViroText node over
// the button, so copy can change without a PNG rebuild.
export type ButtonFaceId = ${entries.map(([id]) => `'${id}'`).join(' | ')};
export type ButtonFaceState = 'rest' | 'hover' | 'active';

export const BUTTON_FACE: Record<ButtonFaceId, Record<ButtonFaceState, number>> = {
${body}
};
`,
  );
  console.log(`\n${entries.length} buttons × 3 states → ${PNG_DIR}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
