// Expo's ambient types, referenced from a file the repo owns.
//
// `expo-env.d.ts` carries the same reference, but it is generated by the Expo
// CLI and gitignored, so a cold clone does not have it: `pnpm install
// --frozen-lockfile && pnpm typecheck` used to fail with ten TS2322s in
// components/splash/MoyoSplash.tsx, where a CSS-animation object had nowhere to
// land without `expo/types` (docs/issues/2026-09-13-cold-install-typecheck-moyosplash.md).
// A developer who has ever run the app has the generated file and cannot see it.
//
// Duplicating one line here is harmless — a repeated `/// <reference>` resolves
// to the same declarations — and it means the typecheck no longer depends on
// whether someone has run `expo start` in this checkout.
/// <reference types="expo/types" />
