/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChaptersLabRouteImport } from './routes/chapters-lab'
import { Route as ChildrensPrivacyRouteImport } from './routes/childrens-privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForParentsRouteImport } from './routes/for-parents'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as GlobeLabRouteImport } from './routes/globe-lab'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MotionLabRouteImport } from './routes/motion-lab'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersLabRoute = ChaptersLabRouteImport.update({
  id: '/chapters-lab',
  path: '/chapters-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrensPrivacyRoute = ChildrensPrivacyRouteImport.update({
  id: '/childrens-privacy',
  path: '/childrens-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForParentsRoute = ForParentsRouteImport.update({
  id: '/for-parents',
  path: '/for-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeLabRoute = GlobeLabRouteImport.update({
  id: '/globe-lab',
  path: '/globe-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionLabRoute = MotionLabRouteImport.update({
  id: '/motion-lab',
  path: '/motion-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chapters-lab': typeof ChaptersLabRoute
  '/childrens-privacy': typeof ChildrensPrivacyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-parents': typeof ForParentsRoute
  '/for-schools': typeof ForSchoolsRoute
  '/globe-lab': typeof GlobeLabRoute
  '/how-it-works': typeof HowItWorksRoute
  '/motion-lab': typeof MotionLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chapters-lab': typeof ChaptersLabRoute
  '/childrens-privacy': typeof ChildrensPrivacyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-parents': typeof ForParentsRoute
  '/for-schools': typeof ForSchoolsRoute
  '/globe-lab': typeof GlobeLabRoute
  '/how-it-works': typeof HowItWorksRoute
  '/motion-lab': typeof MotionLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chapters-lab': typeof ChaptersLabRoute
  '/childrens-privacy': typeof ChildrensPrivacyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-parents': typeof ForParentsRoute
  '/for-schools': typeof ForSchoolsRoute
  '/globe-lab': typeof GlobeLabRoute
  '/how-it-works': typeof HowItWorksRoute
  '/motion-lab': typeof MotionLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chapters-lab'
    | '/childrens-privacy'
    | '/contact'
    | '/faq'
    | '/for-parents'
    | '/for-schools'
    | '/globe-lab'
    | '/how-it-works'
    | '/motion-lab'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chapters-lab'
    | '/childrens-privacy'
    | '/contact'
    | '/faq'
    | '/for-parents'
    | '/for-schools'
    | '/globe-lab'
    | '/how-it-works'
    | '/motion-lab'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chapters-lab'
    | '/childrens-privacy'
    | '/contact'
    | '/faq'
    | '/for-parents'
    | '/for-schools'
    | '/globe-lab'
    | '/how-it-works'
    | '/motion-lab'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChaptersLabRoute: typeof ChaptersLabRoute
  ChildrensPrivacyRoute: typeof ChildrensPrivacyRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForParentsRoute: typeof ForParentsRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  GlobeLabRoute: typeof GlobeLabRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MotionLabRoute: typeof MotionLabRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters-lab': {
      id: '/chapters-lab'
      path: '/chapters-lab'
      fullPath: '/chapters-lab'
      preLoaderRoute: typeof ChaptersLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/childrens-privacy': {
      id: '/childrens-privacy'
      path: '/childrens-privacy'
      fullPath: '/childrens-privacy'
      preLoaderRoute: typeof ChildrensPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-parents': {
      id: '/for-parents'
      path: '/for-parents'
      fullPath: '/for-parents'
      preLoaderRoute: typeof ForParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe-lab': {
      id: '/globe-lab'
      path: '/globe-lab'
      fullPath: '/globe-lab'
      preLoaderRoute: typeof GlobeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-lab': {
      id: '/motion-lab'
      path: '/motion-lab'
      fullPath: '/motion-lab'
      preLoaderRoute: typeof MotionLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChaptersLabRoute: ChaptersLabRoute,
  ChildrensPrivacyRoute: ChildrensPrivacyRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForParentsRoute: ForParentsRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  GlobeLabRoute: GlobeLabRoute,
  HowItWorksRoute: HowItWorksRoute,
  MotionLabRoute: MotionLabRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
