/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersLabRouteImport } from './routes/chapters-lab'
import { Route as GlobeLabRouteImport } from './routes/globe-lab'
import { Route as MotionLabRouteImport } from './routes/motion-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersLabRoute = ChaptersLabRouteImport.update({
  id: '/chapters-lab',
  path: '/chapters-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeLabRoute = GlobeLabRouteImport.update({
  id: '/globe-lab',
  path: '/globe-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionLabRoute = MotionLabRouteImport.update({
  id: '/motion-lab',
  path: '/motion-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapters-lab': typeof ChaptersLabRoute
  '/globe-lab': typeof GlobeLabRoute
  '/motion-lab': typeof MotionLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapters-lab': typeof ChaptersLabRoute
  '/globe-lab': typeof GlobeLabRoute
  '/motion-lab': typeof MotionLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapters-lab': typeof ChaptersLabRoute
  '/globe-lab': typeof GlobeLabRoute
  '/motion-lab': typeof MotionLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chapters-lab' | '/globe-lab' | '/motion-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chapters-lab' | '/globe-lab' | '/motion-lab'
  id: '__root__' | '/' | '/chapters-lab' | '/globe-lab' | '/motion-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChaptersLabRoute: typeof ChaptersLabRoute
  GlobeLabRoute: typeof GlobeLabRoute
  MotionLabRoute: typeof MotionLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters-lab': {
      id: '/chapters-lab'
      path: '/chapters-lab'
      fullPath: '/chapters-lab'
      preLoaderRoute: typeof ChaptersLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe-lab': {
      id: '/globe-lab'
      path: '/globe-lab'
      fullPath: '/globe-lab'
      preLoaderRoute: typeof GlobeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-lab': {
      id: '/motion-lab'
      path: '/motion-lab'
      fullPath: '/motion-lab'
      preLoaderRoute: typeof MotionLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChaptersLabRoute: ChaptersLabRoute,
  GlobeLabRoute: GlobeLabRoute,
  MotionLabRoute: MotionLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
