// AUTO-GENERATED by tooling/icon-atlas/build-buttons.mjs — do not edit.
// Button faces for <ViroButton>: a rounded plate and the lucide glyph, one PNG
// per state. The LABEL is not here — the panel draws it as a ViroText node over
// the button, so copy can change without a PNG rebuild.
export type ButtonFaceId = 'pen' | 'highlighter' | 'eraser' | 'undo' | 'redo' | 'clear' | 'ask';
export type ButtonFaceState = 'rest' | 'hover' | 'active';

export const BUTTON_FACE: Record<ButtonFaceId, Record<ButtonFaceState, number>> = {
  'pen': {
    rest: require('./png/pen-rest.png'),
    hover: require('./png/pen-hover.png'),
    active: require('./png/pen-active.png'),
  },
  'highlighter': {
    rest: require('./png/highlighter-rest.png'),
    hover: require('./png/highlighter-hover.png'),
    active: require('./png/highlighter-active.png'),
  },
  'eraser': {
    rest: require('./png/eraser-rest.png'),
    hover: require('./png/eraser-hover.png'),
    active: require('./png/eraser-active.png'),
  },
  'undo': {
    rest: require('./png/undo-rest.png'),
    hover: require('./png/undo-hover.png'),
    active: require('./png/undo-active.png'),
  },
  'redo': {
    rest: require('./png/redo-rest.png'),
    hover: require('./png/redo-hover.png'),
    active: require('./png/redo-active.png'),
  },
  'clear': {
    rest: require('./png/clear-rest.png'),
    hover: require('./png/clear-hover.png'),
    active: require('./png/clear-active.png'),
  },
  'ask': {
    rest: require('./png/ask-rest.png'),
    hover: require('./png/ask-hover.png'),
    active: require('./png/ask-active.png'),
  },
};
